### ISSUE TITLE
USER STORY 2: High quality images and engaging descriptions

### ISSUE THREAD

**Issue by Gerbil1511** [Gerbil1511/projecttest#2]
User story

As a PARENT/TEACHER, I want to see HIGH QUAITY IMAGES and ENGAGING DESCRIPTIONS of Diversity & Inclusion concepts so that I can get a VISUAL UNDERSTANDING of how to teach these concepts to my child/classroom of children.

**Acceptance Criteria:**

- [ ] A hero section is present at the top of the homepage.
- [ ] The hero section includes a striking image and welcoming headline with an engaging description of the site's purposes
- [ ] Two Bootstrap card items display the basic definitions of Diversity and Inclusion in an uncluttered manner.
- [ ] There are prominent "Book a Talk" and "Volunteer with us" CTA buttons that directs users to a booking form.

**Tasks:**

- [ ] Design and implement a hero section with a high-quality image that reflects the site's theme, headline and description.
- [ ] Ensure the hero section design is visually appealing and aligns with the website's theme.
- [ ] Add a "Book a talk"  and "Volunteer with us" CTA buttons linking to a booking form.
