### ISSUE TITLE
USER STORY 3: Show clear and concise basic concepts of Diversity and Inclusion

### ISSUE THREAD

**Issue by Gerbil1511** [Gerbil1511/projecttest#3]
**User Story**

As a PARENT/TEACHER, I want to UNDERSTAND THE BASIC CONCEPTS of diversity and inclusion so that I can EXPLAIN THEM to my child/classroom of children.

**Acceptance Criteria**

- [ ] The website has a clear and concise introduction to diversity and inclusion.
- [ ] A "Who are we?" section provides a mission statement to clearly reveal why the website and organisation exists.
- [ ] There are simple, age-appropriate definitions and examples.
- [ ] The content is easily accessible from the homepage.

**Tasks**

- [ ] Create a page with sections that provide definitions and examples of Diversity and Inclusion and a section for the organisation's mission statement.
- [ ] Create appealing and responsive designs for the Diversity and Inclusion descriptions and "who are we?" section using Bootstrap.
- [ ] Ensure the page is created as the homepage and accessible from every website page.
