### ISSUE TITLE
USER STORY 4: Show resources that teach diversity and inclusion to primary school age children

### ISSUE THREAD

**Issue by Gerbil1511** [Gerbil1511/projecttest#4]
**User Story**

As a PARENT/TEACHER, I want to FIND RESOURCES that teach diversity and inclusion to primary school age children so that I can INTEGRATE THESE CONCEPTS into conversations with my child/classroom of children.

**Acceptance Criteria**

- [ ] The website has a dedicated page for resources.
- [ ] The resources are clearly organised using Bootstrap grid and card components for consistency and layout responsiveness.
- [ ] The resources are downloadable or linkable to external sources.

**Tasks**

- [ ] Develop a page for resources that is accessible at all times from the nav-bar menu.
- [ ] Create a responsive, clean and organised page with a variety of resources. 
- [ ] Ensure resources are downloadable or linkable (such as book suggestions, posters, informative Youtube videos.
