### ISSUE TITLE
USER STORY 5: Explore relevant external research resources

### ISSUE THREAD

**Issue by Gerbil1511** [Gerbil1511/projecttest#5]
**User Story**

As a PARENT/TEACHER, I want to FIND RELEVANT LINKS to other research that support diversity and inclusion so that I can EXPLORE MORE IN-DEPTH information.

**Acceptance Criteria**

- [ ] The website has a page dedicated to external research.
- [ ] The research page utilises the Bootstrap grid and card components for consistency in layout and responsiveness..
- [ ] The links are active and regularly updated.

**Tasks**

- [ ] Create a page for external research.
- [ ] Create a responsive library featuring some relative external research websites
- [ ] Regularly update the links.
