### ISSUE TITLE
USER STORY 6: Contact details for support and provide feedback

### ISSUE THREAD

**Issue by Gerbil1511** [Gerbil1511/projecttest#6]
**User Story**

As a SITE USER, I need to FIND ESSENTIAL CONTACT INFORMATION details so that I can GET SUPPORT, PROVIDE FEEDBACK , or EXPLORE SOCIAL MEDIA presence.

**Acceptance Criteria**

- [ ] The website contains a dedicated section for contact details (address, email, phone number, social media links)
- [ ] This section is clearly visible and easily accessible from all parts of the website.

**Tasks**

- [ ] Design and place a section for contact details, social media links.
- [ ] Ensure the contact section is clearly visible and accessible from all parts of the website, adhering to common design standards.
