### ISSUE TITLE
USER STORY 7: Book a talk/ Volunteer form

### ISSUE THREAD

**Issue by Gerbil1511** [Gerbil1511/projecttest#7]
**User Story**

As a PARENT/TEACHER I want to book a talk from or volunteer to be a diversity and inclusion ambassador,  using a simple booking inquiry form, so I can organise a visit or get involved.

**Acceptance Criteria**

- [ ] Create a booking form for organising a talk/visit or for volunteering to be an ambassador that is easy to find, and the form is simple and easy to use.
- [ ] The form includes all necessary fields to gather event details: Name, Shool/Organisation, Phone Number, Email, and an option to pick either book a talk or volunteer as an ambassador, and Message box to provide any further information/inquiry. 
- [ ] All fields on the form must be completed before the user can submit the form.
- [ ] When the form is completed correctly, the user is taken to a success page.

**Tasks**

- [ ] Implement a booking form on the website.
- [ ] Implement HTML validation on the form to fit the requirements above.
- [ ] Create a success page to direct users to after submitting the form.
