### ISSUE TITLE
USER STORY 8: Receive Newsletters or updates about new resources or content

### ISSUE THREAD

**Issue by Gerbil1511** [Gerbil1511/projecttest#8]
**User Story**

As a PARENT/TEACHER I want to RECEIVE NEWSLETTERS OR UPDATES about new resources and content so that I can STAY INFORMED about diversity and inclusion.

**Acceptance Criteria**

- [ ] The website has a newsletter signup form, with all necessary fields: Name, Email, Message Us.
- [ ] When the form is completed correctly, the user is taken to a success page.
- [ ] Newsletters are sent regularly with updates on new content.
- [ ] Users can unsubscribe easily.

**Tasks**

- [ ] Create a newsletter signup form.
- [ ] Implement HTML Validation on the form to fit the above requirements.
- [ ] Create a schedule for sending newsletters.
- [ ] Ensure users can unsubscribe easily.
- [ ] Create a success page to direct users to after submitting the form
