### ISSUE TITLE
USER STORY 9: Testimonials/reviews

### ISSUE THREAD

**Issue by Gerbil1511** [Gerbil1511/projecttest#9]
**User Story**

As a PROSPECTIVE VOLUNTEER/CUSTOMER, I want to read testimonials and reviews from other customers/volunteers, so I can gauge the experiences of others and feel more confident about booking a talk or becoming a volunteer.

**Acceptance Criteria**

- [ ] The website includes a responsive section dedicated to displaying customer testimonials and reviews using Bootstrap grid.
- [ ] Testimonials are clearly visible and presented in a format that is responsive, easy to read and navigate

**Tasks**

- [ ] Create a static section on the website for customer testimonials.
- [ ] Populate this section with a selection of pre-written testimonials.
